---
- name: Ejecutar comando AS400
  hosts: all
  tasks:
    - name: Ejecutar comando en AS400
      ibm.power_ibmi.ibmi_cl_command:
        cmd: 'WRKOBJBRM OBJ(*ALL) SLTDATE(FROMDATE(100124)) TODATE(110124)) SAVSTS(*ALL) SORT(*LIB) OUTPUT(*PRINT)'
      register: result

    - name: Mostrar resultado
      ansible.builtin.debug:
        var: result
