---
name: leer spool
hosts: CRI400G
tasks:
  - name: Leer spool
    ibm.power_ibmi.ibmi_sql_query:
      sql: "SELECT JOB_NAME, JOB_NUMBER, SPOOLED_FILE_NAME, OUTPUT_QUEUE, USER_NAME
          FROM QSYS2.OUTPUT_QUEUE_ENTRIES
          WHERE USER_NAME = 'TU_USUARIO'
          ORDER BY JOB_NUMBER DESC
          FETCH FIRST ROW ONLY"
    register: spooldetalis

  - name: Mostrar resultado
    ansible.builtin.debug:
      var: spooldetalis

  